export const ROLES = {
  ADMIN: "ADMIN",
  MANAGER: "MANAGER",
  EMPLOYEE: "EMPLOYEE",
};

export const RECORD_TYPES = {
  INCOME: "INCOME",
  EXPENSE: "EXPENSE",
};

export const RECORD_CATEGORIES = {
  SALARY: "SALARY",
  INVESTMENT: "INVESTMENT",
  OPERATIONS: "OPERATIONS",
  MARKETING: "MARKETING",
  OTHER: "OTHER",
};
